# Digital Ocean App Platform Specification
# Auto-deploy from GitHub with single web service component

name: vue-express-starter
region: nyc  # Change to your preferred region (nyc, sfo, ams, sgp, etc.)

# ============================================================================
# Web Service - Combined Backend + Frontend + Database
# ============================================================================
services:
  - name: web
    # Build configuration
    dockerfile_path: Dockerfile.appplatform
    source_dir: /
    github:
      branch: main  # Change to your branch
      deploy_on_push: true
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME  # Update this!

    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/month - upgrade to basic-xs ($12/month) for production

    # Port configuration
    http_port: 8080

    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 60  # Allow time for database init and migrations
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # IMPORTANT: Environment variables should be set in DO Console
    # Settings > Environment Variables (set at APP LEVEL, not service level)
    #
    # Required variables:
    # - DB_NAME (e.g., "starter")
    # - DB_USER (e.g., "starter_user")
    # - DB_PASSWORD (encrypted)
    # - DB_ROOT_PASSWORD (encrypted)
    # - SERVER_PORT (e.g., "3001")
    # - CORS_ORIGIN (e.g., "https://yourapp.ondigitalocean.app")
    # - JWT_SECRET (encrypted, minimum 32 characters)
    # - SEED_DATABASE (e.g., "true" for ephemeral storage)
    # - ADMIN_EMAIL (encrypted, e.g., "admin@example.com")
    # - ADMIN_PASSWORD (encrypted, minimum 8 characters)
    #
    # Note: DO NOT set DATABASE_URL - it's constructed automatically in docker-entrypoint.sh

# ============================================================================
# Alerts (Optional)
# ============================================================================
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

# ============================================================================
# Deployment Notes
# ============================================================================
# 1. Update the github.repo field above with your repository
# 2. Set all environment variables in DO Console (Settings > Environment Variables)
# 3. Set variables at APP LEVEL (not service level) to prevent overrides
# 4. Use encrypted storage for: DB_PASSWORD, DB_ROOT_PASSWORD, JWT_SECRET, ADMIN_EMAIL, ADMIN_PASSWORD
# 5. Keep SEED_DATABASE=true to recreate admin user on every deployment (ephemeral storage)
# 6. For production with persistent data, use a managed database and set SEED_DATABASE=false
# 7. Database data is LOST on every deployment due to ephemeral storage
# 8. SSL/HTTPS is handled automatically by App Platform
